# Setup
title:               H
tagline:             'None'
description:         'None'
url:                 http://hidekihill.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

sidebar_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
