# Setup
title:               Hideki Hill
tagline:             'pages'
description:         'Jump to'
# url:                 http://hidekihill.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

sidebar_links:
  - title: "Home"
    url: "/"
  - title: "Contact"
    url: "/contact/"
  - title: "Projects"
    url: "/projects/"


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
